[package]
name = "solana-nice-address"
version = "0.1.0"
description = "Generate Nice Solana Address By Template"
edition = "2018"
publish = false

[dependencies]
clap = "2.33.1"
num_cpus = "1.13.0"
solana-sdk = "1.7.15"

[profile.release]
lto = true
codegen-units = 1
